stages:
  - build
  - release

build:
  stage: build
  image: archlinux:latest
  script:
    - pacman -Syu --noconfirm
    - pacman -S --noconfirm python python-pip python-pyqt6 binutils
    - pip install pyinstaller --break-system-packages
    - pyinstaller --onefile --windowed --name DoomLauncher-Linux doom_launcher_qt.py
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build
      artifacts: true
  script:
    - mv dist/DoomLauncher-Linux dist/DoomLauncher-Linux-$CI_COMMIT_TAG
  artifacts:
    paths:
      - dist/
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Lanzamiento de la versión $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
  rules:
    - if: $CI_COMMIT_TAG
