image: archlinux:latest

.build_template: &build_script
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm python python-pip python-pyqt6 binutils
  - pip install pyinstaller --break-system-packages
  - pyinstaller --onefile --windowed --name DoomLauncher-Linux-$CI_COMMIT_REF_SLUG doom_launcher_qt.py

stages:
  - build
  - release

build_main:
  stage: build
  script:
    - *build_script
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "Creando Release para el tag $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Lanzamiento automático de la versión $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'DoomLauncher-Linux-$CI_COMMIT_TAG'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/dist/DoomLauncher-Linux-${CI_COMMIT_REF_NAME}?job=build_for_release'
  rules:
    - if: $CI_COMMIT_TAG

build_for_release:
  stage: build
  script:
    - *build_script
  artifacts:
    paths:
      - dist/
    expire_in: 7 days
  rules:
    - if: $CI_COMMIT_TAG
